# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginDemoApp

  target 'LoginDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginDemoAppUITests' do
    # Pods for testing
  end

    pod 'FBSDKLoginKit'
    pod 'FacebookLogin'
    
end
